name: instructscore_visualizer_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.4.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h5eee18b_5
  - ca-certificates=2024.2.2=hbcca054_0
  - comm=0.2.2=pyhd8ed1ab_0
  - debugpy=1.6.7=py312h6a678d5_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.5.0=h6a678d5_0
  - importlib-metadata=7.1.0=pyha770c72_0
  - importlib_metadata=7.1.0=hd8ed1ab_0
  - ipykernel=6.29.3=pyhd33586a_0
  - ipython=8.22.2=pyh707e725_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jupyter_client=8.6.1=pyhd8ed1ab_0
  - jupyter_core=5.5.0=py312h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - openssl=3.0.13=h7f8727e_0
  - packaging=24.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=23.3.1=py312h06a4308_0
  - platformdirs=4.2.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - python=3.12.2=h996f2a0_0
  - pyzmq=25.1.2=py312h6a678d5_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py312h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.12=h1ccaba5_0
  - tornado=6.3.3=py312h5eee18b_0
  - traitlets=5.14.2=pyhd8ed1ab_0
  - typing_extensions=4.11.0=pyha770c72_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.41.2=py312h06a4308_0
  - xz=5.4.6=h5eee18b_0
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - absl-py==2.1.0
      - accelerate==0.29.1
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - annotated-types==0.6.0
      - appdirs==1.4.4
      - astunparse==1.6.3
      - attrs==23.2.0
      - blessed==1.20.0
      - blinker==1.7.0
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - contourpy==1.2.1
      - cycler==0.12.1
      - cython==0.29.36
      - daal==2024.2.0
      - datasets==2.18.0
      - deepspeed==0.14.0
      - dill==0.3.8
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - filelock==3.13.3
      - fire==0.6.0
      - flask==3.0.3
      - flask-cors==4.0.0
      - flatbuffers==24.3.25
      - fonttools==4.51.0
      - frozenlist==1.4.1
      - fsspec==2024.2.0
      - gast==0.5.4
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-pasta==0.2.0
      - gpustat==1.1.1
      - grpcio==1.62.1
      - h5py==3.10.0
      - hjson==3.1.0
      - huggingface-hub==0.22.2
      - idna==3.6
      - itsdangerous==2.1.2
      - jinja2==3.1.3
      - joblib==1.4.0
      - keras==3.1.1
      - kiwisolver==1.4.5
      - libclang==18.1.1
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.8.4
      - mdurl==0.1.2
      - ml-dtypes==0.3.2
      - mpmath==1.3.0
      - multidict==6.0.5
      - multiprocess==0.70.16
      - namex==0.0.7
      - networkx==3.3
      - ninja==1.11.1.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.535.133
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - opt-einsum==3.3.0
      - optree==0.11.0
      - pandas==2.2.1
      - peft==0.10.0
      - pillow==10.3.0
      - protobuf==4.25.3
      - psutil==5.9.8
      - py-cpuinfo==9.0.0
      - pyarrow==15.0.2
      - pyarrow-hotfix==0.6
      - pydantic==2.6.4
      - pydantic-core==2.16.3
      - pynvml==11.5.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyyaml==6.0.1
      - regex==2023.12.25
      - requests==2.31.0
      - rich==13.7.1
      - safetensors==0.4.2
      - scikit-learn==1.4.1.post1
      - scipy==1.13.0
      - sentencepiece==0.2.0
      - sentry-sdk==1.44.1
      - setproctitle==1.3.3
      - shtab==1.7.1
      - smmap==5.0.1
      - sympy==1.12
      - tbb==2021.12.0
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.16.1
      - termcolor==2.4.0
      - threadpoolctl==3.4.0
      - tokenizers==0.15.2
      - torch==2.2.2
      - tqdm==4.66.2
      - transformers==4.39.3
      - trl==0.8.1
      - tyro==0.8.2
      - tzdata==2024.1
      - urllib3==2.2.1
      - wandb==0.16.6
      - werkzeug==3.0.2
      - wrapt==1.16.0
      - xxhash==3.4.1
      - yarl==1.9.4
